// HeaderReducer
export const STATE_MODAL_SIGNUP = 'STATE_MODAL_SIGNUP';
export const STATE_MODAL_SIGNIN = 'STATE_MODAL_SIGNIN';
export const STATE_MODAL_RESTOREPASS = 'STATE_MODAL_RESTOREPASS';
export const CHANGE_STATE_MODAL_RESET_PASSW = 'CHANGE_STATE_MODAL_RESET_PASSW';

export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_NAME = 'SAVE_NAME';

export const STATE_MODAL_USE = 'STATE_MODAL_USE'
export const STATE_MODAL_BUY = 'STATE_MODAL_BUY'